Pronia/Pronia/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Pronia.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Pronia/Pronia/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Pronia.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Pronia/Pronia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Pronia - Plant Store Bootstrap 5 Template</title>
    <meta name="robots" content="index, follow" />
    <meta name="description"
          content="Pronia plant store bootstrap 5 template is an awesome website template for any home plant shop." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Favicon -->
    <link rel="shortcut icon"
          type="image/x-icon"
          href="assets/images/favicon.ico" />

    <!-- CSS
    ============================================ -->

    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/assets/css/Pe-icon-7-stroke.css" />
    <link rel="stylesheet" href="~/assets/css/animate.min.css" />
    <link rel="stylesheet" href="~/assets/css/swiper-bundle.min.css" />
    <link rel="stylesheet" href="~/assets/css/nice-select.css" />
    <link rel="stylesheet" href="~/assets/css/magnific-popup.min.css" />
    <link rel="stylesheet" href="~/assets/css/ion.rangeSlider.min.css" />
                                 
    <!-- Style CSS -->           
    <link rel="stylesheet" href="~/assets/css/style.css" />
</head>

<body>
    @await Component.InvokeAsync("Header")
    @RenderBody()
    @await Component.InvokeAsync("Footer") 
</body>
</html>